myFirstSite/myFirstSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls',namespace="polls")),
]

myFirstSite/polls/urls.py
from django.conf.urls import url
from myFirstSite import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from . import views

urlpatterns=[
#    url(r'^$',views.IndexView.as_view(),name="index"),    #127.0.0.1/polls/
    url(r'^$', views.index, name="index"),  # 127.0.0.1/polls/
    url(r'^logged_in$',views.index_after, name="index_after"),  # 127.0.0.1/polls/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^results/$', views.ResultsView.as_view(), name="results"),
    url(r'^index_final$', views.ResultsView.as_view(), name="index_final"),  # 127.0.0.1/polls/
 #   url(r'^(?P<candidate_id>[0-9]+)/$', views.image_v, name="image_v"),
    url(r'^votes/$', views.votes, name="votes"),
    url(r'^login/$', auth_views.login,name="login"),
  #  url(r'^logout/$', auth_views.logout, {'template_name':'polls/log_out.html'}, name="logout"),
 #   url(r'^logout/$', views.logout, name="logout"),
    url(r'^logout/$', views.LogOutView.as_view(), name="logout"),

]
#{'template_name':'polls/log_out.html'}
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myFirstSite/polls/models.py
from django.db import models
from django.contrib.auth.models import User

class Candidate(models.Model):
    assigned_number = models.IntegerField(default=1)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    vote_count = models.IntegerField(default=0)
    candidate_image = models.ImageField(upload_to='static/polls/images/')
    candidate_image2 = models.CharField(max_length=1000, default='')
    hit_count = models.IntegerField(default=0)
    def __str__(self):
        return self.first_name + " " + self.last_name

class Voter(models.Model):
    user = models.ForeignKey(User)
    choosen = models.ForeignKey(Candidate)

myFirstSite/polls/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.CharField(widget=forms.EmailInput)

    class Meta:
        model = User
        fields = ['username','email','password']

myFirstSite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import auth
from django.views import generic
from .forms import UserForm
from .models import Candidate,Voter
from django.template import loader

#class IndexView(generic.ListView):
#    candidates = Candidate.objects.all()
#    context = {'candidates': candidates}
#    def get(self,request):
#        return render(request,"polls/index.html",self.context)

def index(request):
    candidates = Candidate.objects.all()
    context = {'candidates': candidates}
    return render(request, 'polls/index.html',context)

def index_after(request):
    candidates=Candidate.objects.all()
    context = {'candidates': candidates}
    return render(request,'polls/index_after.html',context)

class ResultsView(generic.ListView):
    candidates=Candidate.objects.all()
    context = {'candidates': candidates}
    def get(self,request):
        return render(request,"polls/results.html",self.context)

def votes(request):
#    candidate = get_object_or_404(Candidate)
    candidates=Candidate.objects.all()
##    user_id = [user.id for user in Voter.objects.filter(poll__id=poll_id)]
    if Voter.objects.filter(user_id=request.user.id).exists():
        return render(request, 'polls/results.html',{'candidates':candidates,'error_message': "Sorry, but you have already voted."})

    try:
        selected_choice = candidates.get(pk=request.POST['contestant'])
    except:
        return render(request,'polls/index_after.html',{'candidates':candidates,'error_message':"Please select a choice now"})
    else:
        # if user haven't voted yet then allow
        selected_choice.vote_count += 1
        selected_choice.save()
        v = Voter(user=request.user,choosen=selected_choice)
        v.save()
        return render(request,"polls/results.html",{'candidates':candidates})
        # else cannot allow to vote again..only redo

    #return HttpResponseRedirect(reverse('polls:results'),args=(selected_choice))

class UserFormView(generic.View):
    form_class = UserForm
    template_name = 'polls/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            #clean the data
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # return user objects if crediential are correct
            user = authenticate(username=username, email=email, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('polls:index_after')# why use redirect

        return render(request,self.template_name, {'form':form})

def logout(request):
    auth.logout(request)
    return render(request,'polls/log_out.html')

class LogOutView(generic.View):
    template_name = 'polls/log_out.html'
    def get(self, request):
        return render(request,self.template_name)
     #   return redirect('polls:logout')



##def image_view(request):
##    candidates=Candidate.objects.all()
## #   selected_choice = candidates.get(pk=request.POST['contestant'])
##    num_visits=request.session.get('num_visits',0)
##    request.session['num_visits']=num_visits+1
##  #  candidates.hit_count = num_visits
###    Candidate.objects.filter(pk=candidate.pk).update(hit_count=F('hit_count')+1)
###    candidate.hit_count += 1
##    return render(request,"polls/results.html",context={'candidates':candidates,'num_visits':num_visits})

#def image_v(request,candidate_id):
#    candidate=get_object_or_404(Candidate,pk=candidate_id)
#    return render(request,'polls/result.html',{'candidate':candidate})

myFirstSite/polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>2017 Miss Chinese Beauty Pageant</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'polls/thumbnail-gallery.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        var likes=0;
        function like() {
            document.getElementById("show").innerHTML=likes;
            likes = likes + 1;
        }
     </script>
</head>

<body>
  
<br>
{% include "polls/header.html" %}
<!--
<div class="jumbotron">
    <div class="container">
       <!--div class="row">
           <div class="col-md-4"><a href="{% static 'polls/images/Desertsmall.jpg' %}"><img src="{% static 'polls/images/Desertsmall.jpg' %}"></a></div>
           <div class="col-md-4"><a href="{% static 'polls/images/Koalasm.jpg' %}"><img src="{% static 'polls/images/Koalasm.jpg' %}"></a></div>
           <div class="col-md-4"><a href="{% static 'polls/images/Penguinssmall.jpg' %}"><img src="{% static 'polls/images/Penguinssmall.jpg' %}"></a></div>

           <!-- LikeBtn.com BEGIN -->
           <!--span class="likebtn-wrapper" data-theme="squarespace" data-identifier="item_1"></span>
           <!--script>(function(d,e,s){if(d.getElementById("likebtn_wjs"))return;a=d.createElement(e);m=d.getElementsByTagName(e)[0];a.async=1;a.id="likebtn_wjs";a.src=s;m.parentNode.insertBefore(a, m)})(document,"script","//w.likebtn.com/js/w/widget.js");</script>
            <!-- LikeBtn.com END -->
      <!--/div-->
        {% block main_content %}
        {% endblock %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
        <script>
            baguetteBox.run('.tz-gallery');
        </script>
      {% include "polls/footer.html" %}
  </body>
</html>

myFirstSite/polls/templates/polls/base_after.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>2017 Miss Chinese Beauty Pageant</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        var likes=0;
        function like() {
            document.getElementById("show").innerHTML=likes;
            likes = likes + 1;
        }
     </script>
</head>

<body>

<br>
{% include "polls/header_after.html" %}

        {% block main_content %}
        {% endblock %}


        <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
        <script>
            baguetteBox.run('.tz-gallery');
        </script>

      {% include "polls/footer.html" %}


  </body>
  </html>

myFirstSite/polls/templates/polls/base_logging.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>2017 Miss Chinese Beauty Pageant</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        var likes=0;
        function like() {
            document.getElementById("show").innerHTML=likes;
            likes = likes + 1;
        }
     </script>
</head>

<body>
<br>
{% include "polls/header.html" %}
<!--
<div class="jumbotron">
    <div class="container">
       <!--div class="row">
           <div class="col-md-4"><a href="{% static 'polls/images/Desertsmall.jpg' %}"><img src="{% static 'polls/images/Desertsmall.jpg' %}"></a></div>
           <div class="col-md-4"><a href="{% static 'polls/images/Koalasm.jpg' %}"><img src="{% static 'polls/images/Koalasm.jpg' %}"></a></div>
           <div class="col-md-4"><a href="{% static 'polls/images/Penguinssmall.jpg' %}"><img src="{% static 'polls/images/Penguinssmall.jpg' %}"></a></div>

           <!-- LikeBtn.com BEGIN -->
           <!--span class="likebtn-wrapper" data-theme="squarespace" data-identifier="item_1"></span>
           <!--script>(function(d,e,s){if(d.getElementById("likebtn_wjs"))return;a=d.createElement(e);m=d.getElementsByTagName(e)[0];a.async=1;a.id="likebtn_wjs";a.src=s;m.parentNode.insertBefore(a, m)})(document,"script","//w.likebtn.com/js/w/widget.js");</script>
            <!-- LikeBtn.com END -->
      <!--/div-->
        {% block main_content %}
        {% endblock %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
        <script>
            baguetteBox.run('.tz-gallery');
        </script>
      {% include "polls/footer.html" %}
  </body>
</html>

myFirstSite/polls/templates/polls/form-template.html
<h2>NEW USER REGISTRATION</h2>
<br>
<br>
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag}}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

myFirstSite/polls/templates/polls/header.html
{% load staticfiles %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
  <a class="navbar-brand" href="{% url 'polls:index' %}"><STRONG>  <img src="http://sosokanapp.com/assets/images/logo.png" width="125" border="0" align="center"  /></STRONG></a>
        <!-- Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
        </button>

      </div>

      <!--Items
      <div class="collaspe navbar-collaspe" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'polls:index' %}">
                 <span class="glyphicon glyphicon-cd" aria-hidden="false"></span>
                 Contestants
              </a>
            </li>
          </ul>
      -->
<!--
          <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
              <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Search</button>

          </form>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="#">
                 <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                 Logout
              </a>
            </li>
          </ul>
-->
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="{% url 'polls:login' %}">
                 <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                 LOGIN
              </a>
            </li>
          </ul>



      </div>
    </div>
</nav>

myFirstSite/polls/templates/polls/header_after.html
{% load staticfiles %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'polls:index' %}"><STRONG>  <img src="http://sosokanapp.com/assets/images/logo.png" width="125" border="0" align="center"  /></STRONG></a>

        <!-- Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
        </button>
      </div>

      <!--Items
      <div class="collaspe navbar-collaspe" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'polls:index' %}">
                 <span class="glyphicon glyphicon-cd" aria-hidden="false"></span>
                 Contestants
              </a>
            </li>
          </ul>
      -->
<!--
          <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
              <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Search</button>

          </form>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="#">
                 <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                 Logout
              </a>
            </li>
          </ul>
-->
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="{% url 'polls:logout' %}">
                 <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                 Logout
              </a>
            </li>
          </ul>



      </div>
    </div>
</nav>

myFirstSite/polls/templates/polls/header_logging.html
{% load staticfiles %}
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'polls:index' %}"><STRONG>  <img src="http://sosokanapp.com/assets/images/logo.png" width="125" border="0" align="center"  /></STRONG></a>

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--  <div class="navbar-brand">Miss Chinese Beauty Pageant</div>
        a class="navbar-brand" href="#">Project name</a
          img src="{% static 'polls/images/missbeautypageantsmalllong.jpg' %}"-->
        </div>
      </div>
    </nav>

myFirstSite/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load staticfiles %}
{% block main_content %}

<div class="container gallery-container">
</div>

<p class="page-description text-center">
  <img src="http://www.sosokanapp.com/assets/images/beautypageant.jpg" width=400 alt=""/>
</p>
    <p class="page-description text-center">
      <img src="http://www.sosokanapp.com/assets/images/topbanner.jpg" width=400 alt=""/>
    </p>
    <div class="tz-gallery">

        <div class="row">
            {% for contestant in candidates %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a class="lightbox" href="{{contestant.candidate_image2}}">
                        <img src="{{contestant.candidate_image.url}}" width=400 alt="{{contestant.first_name}}"/>
                    </a>
                    <div class="caption">
                    <h4><p class="page-description text-center">#{{contestant.assigned_number}}. {{contestant.first_name}} {{contestant.last_name}}</p></h4>


                              <form action="{% url 'polls:login' %}">
                                  <p class="page-description text-center">
                              <input type="image" src="http://www.clker.com/cliparts/c/l/Y/w/j/p/orange-heart-hi.png" width=60>{{contestant.vote_count}}
                                  </p>
                              </form>
                              <form action="{% url 'polls:login' %}">
                                  <p class="page-description text-center">VOTE
                                  </p>
                              </form>
                 </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>



    <p class="page-description text-center">
      <a href="http://www.sosokanapp.com/index_cn.html" target="_blank">
            <img src="http://www.sosokanapp.com/assets/images/bottombanner.jpeg" width=400 border="0" align="center"/>
    </p>


</div>


<!--
<div class="container">
    {% for contestant in candidates %}
        {% if forloop.counter|divisibleby:3 %}
        <div class="row">
        {% endif %}
            <div class="col-md-4">
                <div class="picture w3-card-4" style="width:20rem">
                    <a class="lightbox" href="{{contestant.candidate_image.url}}">
                        <img class="card-img-top" src="{{contestant.candidate_image.url}}" style="width:19rem" class="center-block img-responsive">
                    </a>
                    <div class = "card-block">
                        <h4>#{{contestant.assigned_number}} {{contestant.first_name}} {{contestant.last_name}}</h4>
                    </div>
                    <div class = "card-footer">
                       <p style="font-size:120%">
                           <img src="static/polls/images/heart-transparent.png" style="height:15px;width:15px"> {{contestant.vote_count}}
                       </p>
                    </div>
                </div>
            </div>
        {% if forloop.counter|divisibleby:3 %}
        </div>
        <br>
        {% endif %}
    {% endfor %}
</div>
-->

{% endblock %}

myFirstSite/polls/templates/polls/index_after.html
{% extends "polls/base_after.html" %}
{% load staticfiles %}
{% block main_content %}

<div class="container gallery-container">


      <p class="page-description text-center">
        <img src="http://www.sosokanapp.com/assets/images/topbanner.jpg" width=400 alt=""/>
      </p>

    <div class="tz-gallery">

      <form action = "{% url 'polls:votes' %}" method="post">
      {% csrf_token %}

        <div class="row">
          <p class="page-description text-center">
            <img src="http://www.sosokanapp.com/assets/images/pickone.jpg" width=400 alt=""/>
          </p>

            {% for contestant in candidates %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a class="lightbox" href="{{contestant.candidate_image.url}}">
                        <img src="{{contestant.candidate_image.url}}" width=500 alt="{{contestant.first_name}}"/>
                    </a>
                    <div class="caption">
                      <h4><p class="page-description text-center">#{{contestant.assigned_number}}. {{contestant.first_name}} {{contestant.last_name}}</p></h4>
                    <div class = "card-block">

                    </div>

                            <p class="page-description text-center">
                            <input type="image" src="http://www.clker.com/cliparts/c/l/Y/w/j/p/orange-heart-hi.png" name="contestant" id="contestant{{forloop.counter}}" value ="{{contestant.id}}" width=60>{{contestant.vote_count}}
                          </p>
                          <p class="page-description text-center">Tap on the heart to Vote!</p>

                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>

    <p class="page-description text-center">
      <a href="http://www.sosokanapp.com/index_cn.html" target="_blank">
            <img src="http://www.sosokanapp.com/assets/images/bottombanner.jpeg" width=400 border="0" align="center"/>
    </p>



</div>

<!--
<div class="container">
    <form action = "{% url 'polls:votes' %}" method="post">
    {% csrf_token %}
    <div class="row">
        <h3 align="center"><b>Select your favorite contestant below.</b></h3>
        <div class="block" align="center">
            <label style="display:inline-block; vertical-align:middle; font-size: 22px;">Then click</label>
            <input type ="submit" class="btn btn-success" value="CONFIRM" style="text-align:center; vertical-align:middle; font-size:18px"/>
        </div>
    </div>
        <br>
    {% for contestant in candidates %}
        {% if forloop.counter|divisibleby:3 %}
        <div class="row">
        {% endif %}
            <div class="col-md-4">
                <div class="picture w3-card-4" style="width:20rem">
                    <a class="lightbox" href="{{contestant.candidate_image.url}}">
                        <img class="card-img-top" src="{{contestant.candidate_image.url}}" style="width:19rem"   class="center-block img-responsive">
                    </a>
                    <br>
                    <div class = "card-block">
                        <br>
                        <input type="radio" name="contestant" id="contestant{{forloop.counter}}" value ="{{contestant.id}}"/>
                        <label for="contestant{{forloop.counter}}">#{{contestant.assigned_number}} {{contestant.first_name}} {{contestant.last_name}}</label><br>
                    </div>
                    <div class = "card-footer">
                       <p style="font-size:120%">
                           <img src="static/polls/images/heart-transparent.png" style="height:15px; width:15px"> {{contestant.vote_count}}
                       </p>
                    </div>
                </div>
            </div>
        {% if forloop.counter|divisibleby:3 %}
        </div>
        <br>
        {% endif %}
    {% endfor %}
    </form>
</div>

-->

{% endblock %}

myFirstSite/polls/templates/polls/log_out.html
{% extends 'polls/base.html' %}
{% load staticfiles %}
{% block main_content %}
<div>

  <p class="page-description text-center">
    <img src="http://www.sosokanapp.com/assets/images/thankyou.jpg" width=400 alt=""/>
  </p>
      <p class="page-description text-center">
    <a href="http://www.sosokanapp.com/index-cn.html" target="_blank">
        <img src="http://www.sosokanapp.com/assets/images/moving-banner.gif" width=500 border="0" align="center"/>
      </p>
</div>


<div class="container">
	<h2><p class="page-description text-center">Sponsored and Brought to you by: Sosokan!</p></h2>
	<div class="row">
		<div class="col-sm-12 col-md-offset-3">
			<!--div class="panel panel-default"-->

            <div class="panel-body">

              <a href="http://www.sosokanapp.com/index-cn.html" target="_blank">
                  <img src="http://www.sosokanapp.com/assets/images/hand.png" width=500 border="0" align="center"/>


              </a>
            </div>
            <div class="panel-body">
              <p class="page-description text-center">
                <a href="https://itunes.apple.com/us/app/sosokan-buy-sell-and-trade-in-your-local-commun/id1023454229?mt=8" target="_blank">
                      <img src="http://www.sosokanapp.com/assets/images/download.png" width=250 border="0" align="center"/>
              </p>
              </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myFirstSite/polls/templates/polls/registration_form.html
{% extends 'polls/base_logging.html' %}
{% load staticfiles %}
{% block main_content %}

<div class="container">

	<div class="row">

		<div class="col-sm-12 col-md-offset-3">
			<!--div class="panel panel-default"-->
				<div class="panel-body">


	<!--div class="col-sm-offset-2 col-sm-10">
      <form class="form-signin" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
        <h2 class="form-signin-heading">Please Sign In:</h2>
        <label for="inputEmail" class="sr-only">Email Address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email Address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">
			<a href = "{% url 'polls:index_after' %}">Sign in</a>
		</button>
      </form>
	</div-->

					<!--form class="form-horizontal" action="{% url 'polls:index_after' %}" method="post" enctype="multipart/form-data"-->
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include "polls/form-template.html" %}
						<div class="form-group"></div>
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">
                                    Submit
                                </a>
							</div>
					</form>

				</div>
			</div>

		<!--/div-->
	</div>

</div>
{% endblock %}