website (Bucky) Backup/vote/urls.py
from django.conf.urls import url
from . import views

app_name = 'vote'

urlpatterns = [

        # /vote/
        url(r'^$', views.index, name='index'),

        # /vote/

        # /vote/ID#/
        url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

        url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),


]

website (Bucky) Backup/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vote/', include('vote.urls')),
]

website (Bucky) Backup/vote/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)


    def __str__(self):
        return self.artist + ' - ' + self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website (Bucky) Backup/vote/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index(request):
    all_albums = Album.objects.all()
    return render(request, 'vote/index.html', {'all_albums': all_albums,})

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'vote/detail.html', {'album': album,})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):

        return render(request, 'vote/detail.html', {
            'album': album,
            'error_message': "You did not select a valid song",
    })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'vote/detail.html', {'album': album,})

website (Bucky) Backup/vote/templates/vote/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>2017 Miss Chinese Beauty Pageant</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" type="text/css" href={% static 'vote/style.css' %}/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'vote:index' %}">SOSOKAN</a>
      </div>

      <!--Items -->
      <div class="collaspe navbar-collaspe" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'vote:index' %}">
                 <span class="glyphicon glyphicon-cd" aria-hidden="false"></span>
                 Contestants
              </a>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'vote:index' %}">
                 <span class="glyphicon glyphicon-cd" aria-hidden="false"></span>
                 Gallery
              </a>
            </li>
          </ul>

          <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
              <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Search</button>

          </form>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="#">
                 <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                 Logout
              </a>
            </li>
          </ul>

      </div>
    </div>
</nav>

{% block body %}

{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
</body>
</html>

website (Bucky) Backup/vote/templates/vote/detail.html
{% extends 'vote/base.html' %}

{% block body %}




{% for album in album.album_set.all %}
  <label for="album{{ forloop.counter }}">
    {{ album.album_title }}
    {% if song.is_favorite %}
      <img src="http://i.imgur.com/b9b13Rd.png" />
    {% endif %}
  </label><br>
{% endfor %}

<img src="{{ album.album_logo}}" width=400>
<h1> {{ album.album_title }} </h1>
<h3> {{ album.artist }} </h3>


{% if error_message %}
  <p><strong>{{ error_message}}</strong></p>
{% endif %}

<form action="{% url 'vote:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
      <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
      <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favorite %}
          <img src="http://www.clker.com/cliparts/c/l/Y/w/j/p/orange-heart-hi.png" />
        {% endif %}
      </label><br>
    {% endfor %}
    <input type="submit" value="favorite">
</form>

{% endblock %}

website (Bucky) Backup/vote/templates/vote/index.html
{% extends 'vote/base.html' %}

{% block body %}



<div class="container gallery-container">

    <h1><p class="page-description text-center">2017 Miss Chinese Beauty Pageant</p></h1>

    <p class="page-description text-center">Thumbnails With Title And Description</p>

    <div class="tz-gallery">

        <div class="row">
            {% for album in all_albums %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a class="lightbox" href="{{ album.album_logo}}">
                        <img src="{{ album.album_logo}}" width=500 alt="{{album.album_artist}}"/>
                    </a>
                    <div class="caption">
                    <h4><p class="page-description text-center">{{album.album_title}}</p></h4>
                        <form action="{% url 'vote:favorite' album.id %}" method="post">
                            {% csrf_token %}
                                {% if song.is_favorite %}
                                  <img src="http://www.clker.com/cliparts/D/u/R/8/Y/q/solid-orange-heart-md.png" width=40/>
                                {% endif %}
                              </label><br>
                            <p class="page-description text-center">
                            <input type="image" src="http://www.clker.com/cliparts/c/l/Y/w/j/p/orange-heart-hi.png" width=40>
                          </p>
                        </form>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>

</div>


{% endblock %}