website/vote/urls.py
from django.conf.urls import url
from . import views

app_name = 'vote'

urlpatterns = [

        # /vote/
        url(r'^$', views.IndexView.as_view(), name='index'),

        url(r'^register/$', views.UserFormView.as_view(), name='register'),


        url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
        # /vote/album/add/
        url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
        # /vote/album/update/
        url(r'album/^(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
        # /vote/album/delete/
        url(r'album/^(?P<pk>[0-9]+)/$', views.AlbumDelete.as_view(), name='album-delete'),


]

website/vote/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('vote:detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.artist + ' - ' + self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/vote/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

website/vote/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .models import Album, Song
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'vote/index.html'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
        model = Album
        template_name = 'vote/detail.html'

class AlbumCreate(CreateView):
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
        model = Album
        success_url = reverse_lazy('vote:index')

class UserFormView(View):
        form_class = UserForm
        template_name = 'vote/registration_form.html'

        # display blank form
        def get(self, request):
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})

        # process form data here
        def post(self, request):
            form = self.form_class(request.POST)

            if form.is_valid():
                #store into local first
                user = form.save(commit=False)

                # cleaned (normalized) data
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user.set_password(password)
                user.save()

                # returns User objects if credentials are correct
                user = authenticate(username=username, password=password)

                if user is not None:

                    if user.is_active:
                        login(request, user)
                        return redirect('vote:index')

            return render(request, self.template_name, {'form': form})

website/vote/templates/vote/album_form.html
{% extends 'vote/base.html' %}


{% block body %}

<div class="container-fluid">

  <div class="row">

    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">

            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'vote/form-template.html' %}
                        <title> Add Album </title>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">Submit</button>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/vote/templates/vote/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>2017 Miss Chinese Beauty Pageant</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
<!--    <link rel="stylesheet" type="text/css" href={% static 'vote/style.css' %}/>  -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript">
    var likes=0;
    function like() {
        document.getElementById("show").innerHTML=likes;
        likes = likes + 1;
    }
 </script>

</head>
<body>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'vote:index' %}"><STRONG>SOSOKAN</STRONG></a>
      </div>

      <!--Items -->
      <div class="collaspe navbar-collaspe" id="topNavBar">
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'vote:index' %}">
                 <span class="glyphicon glyphicon-cd" aria-hidden="false"></span>
                 Contestants
              </a>
            </li>
          </ul>

          <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
              <input type="text" class="form-control" name="q" value="">
            </div>
            <button type="submit" class="btn btn-default">Search</button>

          </form>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="#">
                 <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                 Logout
              </a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="{% url 'vote:register' %}">
                 <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                 Signup
              </a>
            </li>
          </ul>



      </div>
    </div>
</nav>

{% block title %}
{% endblock %}

{% block body %}

{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
</body>
</html>

website/vote/templates/vote/detail.html
{% extends 'vote/base.html' %}

{% block body %}




{% for album in album.album_set.all %}
  <label for="album{{ forloop.counter }}">
    {{ album.album_title }}
    {% if song.is_favorite %}
      <img src="http://i.imgur.com/b9b13Rd.png" />
    {% endif %}
  </label><br>
{% endfor %}

<img src="{{ album.album_logo}}" width=400>
<h1> {{ album.album_title }} </h1>
<h3> {{ album.artist }} </h3>


{% if error_message %}
  <p><strong>{{ error_message}}</strong></p>
{% endif %}

    {% csrf_token %}
    {% for song in album.song_set.all %}
      <label for="song{{ forloop.counter }}">
        {{ song.song_title }}

          <img src="http://www.clker.com/cliparts/c/l/Y/w/j/p/orange-heart-hi.png" />
      </label><br>
    {% endfor %}

{% endblock %}

website/vote/templates/vote/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10"> {{ field }}
    </div>
  </div>
{% endfor %}

website/vote/templates/vote/index.html
{% extends 'vote/base.html' %}

{% block body %}



<div class="container gallery-container">

    <h2><p class="page-description text-center">2017 Miss Chinese Beauty Pageant</p></h2>
    <div class="tz-gallery">

        <div class="row">
            {% for album in object_list %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a class="lightbox" href="{{ album.album_logo}}">
                        <img src="{{ album.album_logo}}" width=500 alt="{{album.album_artist}}"/>
                    </a>
                    <div class="caption">
                    <h4><p class="page-description text-center">{{album.album_title}}</p></h4>

                            <p class="page-description text-center">
                            <input type="image" src="http://www.clker.com/cliparts/c/l/Y/w/j/p/orange-heart-hi.png" width=40>
                          </p>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>

</div>


{% endblock %}

website/vote/templates/vote/login.html
{% extends "blog/base.html" %}

{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
        <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

website/vote/templates/vote/registration_form.html
{% extends 'vote/base.html' %}

{% block title%}<h3><p class="page-description text-center">Register</p></h3>{% endblock %}

{% block body %}

<div class="container-fluid">

  <div class="row">

    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">

            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'vote/form-template.html' %}
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">Submit</button>

        </div>
      </div>
    </div>
  </div>
  {% endblock %}